### ISSUE TITLE
Feature request: renaming data properties

### ISSUE THREAD

**Issue by spustlik** [2blane/OctoPrint-Webhooks#1]
Thank you for great plugin, it seems to be very handy.
You write that it can be used with IFTT, but when i tried it (to show notification in my browser), it seems that IFTT is only accepting json parameters named "value1", "value2", and "value3".
It would be great to add possibility to construct own json payload using some "templating" mechanism or so. For example add something like 
{
  deviceIdentifier: "@deviceId",
  apiSecret: "@apisecret",
  topic: "@eventname",
  message: "@eventdescription",
  extra: @eventjson
}
into user configuration and simple replace...

**Comment by 2blane** [comment]
Great idea! I’ll add that in.

**Comment by 2blane** [comment]
@spustlik I just finished adding this feature. You can now customize the headers and data that are sent in the Webhooks. Should work for your use case.
Also, can you send me the docs you are using for IFTT, would like to build some default configurations for different services (IFTT, Twitter, Slack, etc.). Then, you'd just select the service and it would fill out the settings for you by default.
