### ISSUE TITLE
Human readable @param

### ISSUE THREAD

**Issue by pjolayres** [2blane/OctoPrint-Webhooks#14]
Is there any way to have additional parameters as human readable equivalents of existing parameters? I wanted to setup a notification to be sent to Alexa using Notify Me skill whenever the print has finished. Something like:

>"Your print has finished at around 8:40 pm. It consumed 17.23 meters of filament and took 13:16:54 to complete." 

>"Your print has been paused at 8:40pm pending user intervention"

The only alternative I can think of is to setup a separate local server in the raspberry pi that serves as an intermediary server that transforms the data before sending it off. However, it would be great if the plugin does this by default.

**Comment by 2blane** [comment]
Absolutely!

For each event you can set a custom message. You can do this under the Events section. Inside the message, you can use @param notation to pass in whatever data you want. If you look at the Print Progress Event message you'll see "Your print is @percentCompleteMilestone % complete." This will turn into "Your print is 50 % complete."
![Screen Shot 2020-08-05 at 3 18 53 PM](https://user-images.githubusercontent.com/25189660/89460488-fd389500-d72f-11ea-885a-2cdf58616840.png)

Now, the Event message that you set above is available for use as @message. Go to the Advanced section and make sure in the Data input you use @message like in the screenshot below.
![Screen Shot 2020-08-05 at 3 19 09 PM](https://user-images.githubusercontent.com/25189660/89460621-2f49f700-d730-11ea-9d7e-0fb59210ca63.png)

Does that make sense?

**Comment by pjolayres** [comment]
That is handy. i didn't realize it's possible to use @param in the messages. However, i was referring mostly to the transformation needed to make the other params more human readable. For example,

`currentTime` is defined in milliseconds since epoch, but a human readable version would be:
> February 24, 3:56 PM

`extras.time` is defined in seconds but is hardly intuitive when interpreted by humans. A better presentation would be
> 3:2:15
which, Alexa reads appropriately as a duration of time. Maybe even:
> 3 hours, 2 minutes, and 15 seconds
but the last one is a slippery slope since it will introduce localization bias towards English.

`job.filament.length` is defined in millimeters, but i would rather have Alexa say that in meters. Even better would be if it was available in grams of filament used, but that's probably asking too much since many more variables are involved to compute that.

For the meantime, i have just started a very lightweight node web server in the raspberry pi automatically runs when it powers on. It would be amazing if we didn't have to do that though.

**Comment by 2blane** [comment]
Hmm, this seems like it could get very complicated as each use case would have its own format requirements. Working on something top secret currently, may have something for you in a few months to solve all your problems, but for now an intermediary web server should be the solution to how you are passing on your data.

**Comment by Bob-the-Kuhn** [comment]
@pjolayres - did you ever get your Notify Me webhook to work?

If yes, I'd like to see how you did it.

Right now I'm stuck at the "Invalid JSON for the data header" error message.

I can use the **x-www-form-urlencoded** content type to create individual webhooks for each unique (fixed) message I want to send.   I was hoping to use the JSON content type so that I could use some of the fancier features.

**Comment by Bob-the-Kuhn** [comment]
Never mind ...  I figured it out.

I was being too complicated.
