### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by cibgraphics** [2blane/OctoPrint-Webhooks#2]
Maybe not the entire point of this plugin, but maybe make it possible to send more info through the API like time (remaining/progress/total), name of file being print, etc?

**Comment by 2blane** [comment]
@cibgraphics just added to the list!

**Comment by teamzaure** [comment]
hello would it be possible to have one url per event ? thanks

**Comment by 2blane** [comment]
@teamzaure yes this is on the list. Was going to add the ability to have multiple webhooks defined. This way, you could have one web hook that just responds to Print Started, and another that just responds to Print Finished, etc. This should cover your use case.

**Comment by 2blane** [comment]
@cibgraphics @teamzaure just added a ton of properties that you can include in your webhooks including a snapshot, progress, job details, file metadata, etc. If you come up with anything missing let know.

**Comment by 2blane** [comment]
@teamzaure just pushed an update to allow multiple webhooks. This will allow you to have a different url per event. You can get one web hook working, then just duplicate the web hook, change the url and events enabled and you're good to go.
