### ISSUE TITLE
Custom headers ignored

### ISSUE THREAD

**Issue by stefan-sherwood** [2blane/OctoPrint-Webhooks#22]
I add a new webhook. I change _Advanced → HEADERS_ to:

```
{
  "Content-Type": "application/json",
  "test": "where is this header?"
}
```

But when I click _Send Test Webhook_, the call made to my server does not include the "test" header.

I have tried:
- Saving the Webhook before pressing test (and not saving it before pressing test, same result)
- Restarting the OctoPrint server
- Removing the "snapshot" entry under the DATA json (because that causes another header to be overwritten)

**Comment by stefan-sherwood** [comment]
Hmm...I deleted the webhook and created it anew and now with the identical settings it works fine. I don't know how it got into such a stuck state. Feel free to close if you don't consider it a bug.

**Comment by 2blane** [comment]
Going to merge this with #19
