### ISSUE TITLE
Possibility to fire events to webhook as test

### ISSUE THREAD

**Issue by StefanBols** [2blane/OctoPrint-Webhooks#4]
May be placed in bottom of settings page under title "Test Webhook events".

Under there a radio selector of the different event and a button with the text "Fire test event"-ich.

This way it's possible to test you API endpoint for receiving events from OctoPrint and not starting up the printer each time you want to test your API :-)

**Comment by 2blane** [comment]
@StefanBols working on this as we speak! Thanks for the note and also the pull request!

**Comment by 2blane** [comment]
@StefanBols just released a new update with the ability to test webhook events. Should find it at the bottom of the settings page.

**Comment by StefanBols** [comment]
That was quick! I’ll look into it later, thanks :-)
