### ISSUE TITLE
@Params are not substituted

### ISSUE THREAD

**Issue by staude** [2blane/OctoPrint-Webhooks#5]
I have installed the plugin and want to send the data to my Node Red instance.

In the plugin I have configured the default data

![octo](https://user-images.githubusercontent.com/870951/80966088-1a4d8700-8e14-11ea-8daa-ac61d487e32b.png)

in my node red i receive this data as payload

<img width="290" alt="nodered" src="https://user-images.githubusercontent.com/870951/80966153-394c1900-8e14-11ea-9a7b-2d4ee8d062d5.png">

it looks like the parameters are not substituted for the transmission.

What other information should I provide?

All plugins and Octoprint are up to date. The following plugins are installed.
- Action Command Prompt Support 
- Announcement Plugin
- Anonymous Usage Tracking
- Application Keys Plugin
- Automatic Shutdown
- Backlash autocalibration
- Backup & Restore
- Core Wizard 
- Cost Estimation
- Discovery
- DisplayProgress
- EEPROM Marlin Editor Plugin
- Emergency Stop Button
- Error Tracking
- FileManager
- HeaterTimeout
- LED Strip Control 
- Logging
- Pi Support Plugin
- Printer Safety Check
- Software Update
- STL Viewer
- Themeify
- Virtual Printer
- Webhooks

**Comment by 2blane** [comment]
@staude hmm this is odd. What version of the plugin do you have? I just released an update, it seems to take the software updater a day or so to find the new release so it might not tell you there is an update when there is. Should be version 2.4.0

**Comment by jb18** [comment]
Hi, 

I have the same issue with 2.4.0. No issue with the previous (2.3.0) :)

**Comment by staude** [comment]
i have 2.4.0. installed.

![2020-05-04_1551](https://user-images.githubusercontent.com/870951/80973206-59cda080-8e1f-11ea-8243-7a7f3d6e1ef5.png)

**Comment by 2blane** [comment]
@jb18 @staude AHHHH! it's a weird Python 2/3 issue. I'll get it fixed.

**Comment by 2blane** [comment]
@jb18 @staude Just released a new version 2.5.0 with this fixed. Let me know if you run into any trouble.

**Comment by jb18** [comment]
> @jb18 @staude Just released a new version 2.5.0 with this fixed. Let me know if you run into any trouble.

It works fine :) bug fixed. thx !

**Comment by staude** [comment]
works as expected :) thank you very much.
