### ISSUE TITLE
multiple webhook on local url event

### ISSUE THREAD

**Issue by martinbrd49** [2blane/OctoPrint-Webhooks#9]
Hello,
I tried to use your plugin to send a custom url to an esp8266 module, which contains a program that does not allow the implementation of webhook / api.
(this program is not mine: =>[ Wemos led NotifHour ]( https://byfeel.info/notifheure-v3-diy/)
It is a led display with a wemos
)

Here is the capture of each of my webhooks with a specific function and a precise message for each of them.

When I test each webhook, it works well. Unfortunately, in operation, I only have the webhook which was saved in active in the parameters which is functional.

Do you have another way of proceeding?
thank you in advance, I dream of being able to use it, because it is the only one that I found apart from ifttt that I do not want to use ;)
![Screenshot_8](https://user-images.githubusercontent.com/35396847/82509813-3dad4d00-9b09-11ea-90fa-43668a799860.png)
![Screenshot_9](https://user-images.githubusercontent.com/35396847/82509816-3ede7a00-9b09-11ea-98b2-ff66e34e055f.png)
![Screenshot_10](https://user-images.githubusercontent.com/35396847/82509818-3ede7a00-9b09-11ea-8021-76587d297871.png)

**Comment by 2blane** [comment]
Hey @martinbrd49 I just pushed an update 3.0.2 that should fix this issue. Thanks for pointing it out!
